# Generated by Django 3.2.4 on 2021-06-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruning', models.CharField(max_length=256, null=True)),
                ('pest_management', models.CharField(max_length=256, null=True)),
                ('fertiliser', models.CharField(max_length=256, null=True)),
                ('water_requirement', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.CharField(max_length=256)),
                ('humidity', models.CharField(max_length=256)),
                ('temperature', models.FloatField(verbose_name='in Celsius')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_on_wild_life', models.CharField(max_length=1024)),
                ('effect_on_microclimate', models.CharField(max_length=1024)),
                ('effect_on_soil', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestingCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvesting_method', models.CharField(max_length=1024)),
                ('post_harvest_care', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='HowToPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprouting_conditions', models.CharField(max_length=256, null=True)),
                ('planting_method', models.CharField(choices=[('Direct Seeds', 'Direct Seeds'), ('Grafting', 'Grafting'), ('Cuttings', 'Cuttings')], max_length=40)),
                ('distance_between_plats', models.FloatField(verbose_name='in cms')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_height', models.FloatField(verbose_name='in cms')),
                ('canopy_density', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('canopy_radius', models.FloatField()),
                ('root_structure', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('usage', models.CharField(max_length=1024, null=True)),
                ('pruning', models.CharField(max_length=256, null=True)),
                ('pest_management', models.CharField(max_length=256, null=True)),
                ('fertiliser', models.CharField(max_length=256, null=True)),
                ('water_requirement', models.CharField(max_length=256, null=True)),
                ('sunlight', models.CharField(max_length=256, null=True)),
                ('humidity', models.CharField(max_length=256, null=True)),
                ('temperature', models.FloatField(null=True, verbose_name='in Celsius')),
                ('effect_on_wild_life', models.CharField(max_length=1024, null=True)),
                ('effect_on_microclimate', models.CharField(max_length=1024, null=True)),
                ('effect_on_soil', models.CharField(max_length=1024, null=True)),
                ('average_height', models.FloatField(null=True, verbose_name='in cms')),
                ('canopy_density', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('canopy_radius', models.FloatField(null=True)),
                ('root_structure', models.CharField(max_length=1024, null=True)),
                ('harvesting_method', models.CharField(max_length=1024, null=True)),
                ('post_harvest_care', models.CharField(max_length=1024, null=True)),
                ('nutrition_requirements', models.CharField(max_length=256, null=True)),
                ('soil_type', models.CharField(max_length=512, null=True)),
                ('sprouting_conditions', models.CharField(max_length=256, null=True)),
                ('planting_method', models.CharField(choices=[('Direct Seeds', 'Direct Seeds'), ('Grafting', 'Grafting'), ('Cuttings', 'Cuttings')], max_length=40, null=True)),
                ('distance_between_plats', models.FloatField(null=True, verbose_name='in cms')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrition_requirements', models.CharField(max_length=256)),
                ('soil_type', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
    ]
